# Build + test + package +publish
image: Visual Studio 2015

install:
  -ps : "ls -recurse"

before_build:
  - cmd: nuget restore

build:
  project: HopfieldNetwork.sln
  verbosity: detailed
  
environment:
  COVERALLS_REPO_TOKEN:
    secure: 6Gx3oaDRdtMkwt+eH52ng0d2TMiVApoEmbt12R7Y5OaTT+K6dw65OY4JgbRhqEh6
    
after_test:     
# generate report for MSTest testing framework:
#  -cmd : cd package\OpenCover.4.6.519\tools
  -cmd: packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:HopfieldNetworkTesting/bin/debug/HopfieldNetworkTesting.dll" -output:coverage.xml
# -cmd: C:\Users\appveyor\.nuget\packages\coveralls.io.1.4.2\tools\coveralls.net.exe --opencover coverage.xml
#  -cmd: packages\coveralls.io.1.4.2\tools\coveralls.net.exe --opencover coverage.xml
#  - ps: ls -recurse ./packages
#  - ps: ./packages/OpenCover.4.6.519/tools/OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:HopfieldNetworkTesting/bin/debug/HopfieldNetworkTesting.dll" -output:coverage.xml
        
