# Build + test + package +publish
install:
#  - ps: Install-Package coveralls.io
  - nuget install coveralls.io -version 1.4.2
  - nuget install OpenCover -version 4.6.519 
  
build:
  project: HopfieldNetwork.sln
  verbosity: detailed
  
environment:
  COVERALLS_REPO_TOKEN:
    secure: Xd4a6rSs3WWmqQBSlhfckBIp7KJUssXKsuLL7mHuMQsN9zSitiCamCj5M3JLErbR
    
after_test: 
# generate report for NUnit testing framework:
   -cmd: packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"/noshadow /domain:single HopfieldNetworkTesting\bin\debug\HopfieldNetworkTesting.dll" -output:coverage.xml
    
    
# generate report for MSTest testing framework:
#    -cmd: packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:HopfieldNetworkTesting/bin/debug/HopfieldNetworkTesting.dll" -output:coverage.xml
        
#    - cmd: packages\coveralls.io.1.4.2\tools\coveralls.net.exe --opencover coverage.xml -r %COVERALLS_REPO_TOKEN%    

