#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master
#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build + test + package +publish
image: Visual Studio 2015

before_build:
  - cmd: nuget restore

build:
  project: HopfieldNetwork.sln
  verbosity: detailed

# environment variables
environment:
  COVERALLS_REPO_TOKEN:
    secure: 6Gx3oaDRdtMkwt+eH52ng0d2TMiVApoEmbt12R7Y5OaTT+K6dw65OY4JgbRhqEh6
    
#---------------------------------#
#       tests configuration       #
#---------------------------------#    
after_test:     
# generate report for MSTest testing framework:
   - cmd :
        packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:HopfieldNetworkTesting/bin/debug/HopfieldNetworkTesting.dll" -output:coverage.xml
 
        packages\coveralls.io.1.4.2\tools\coveralls.net.exe --opencover coverage.xml -r %COVERALLS_REPO_TOKEN%
        
        dir/b/s
        
        type C:\projects\hopfieldneuralnetwork-dotnet\TestResults\appveyor_APPVYR-WIN*.trx
        
        type C:\projects\hopfieldneuralnetwork-dotnet\coverage.xml
        
 
